### ISSUE TITLE
Cant build containers

### ISSUE THREAD

**Issue by Stakecraft** [StakeSquid/graphprotocol-mainnet-docker#17]
~/graphprotocol-mainnet-docker$ bash start
```
Step 15/20 : RUN npm i -g @graphprotocol/indexer-cli@0.20.1 --registry https://registry.npmjs.org/ --unsafe-perm=true
 ---> Running in fcb844d20863
npm WARN deprecated pino-multi-stream@6.0.0: No longer supported. Use the multi-stream support in the latest core Pino
npm WARN deprecated fastify-warning@0.2.0: This module renamed to process-warning
/home/graph/.npm-global/bin/graph-indexer -> /home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/bin/graph-indexer

> @graphprotocol/cost-model@0.1.14 install /home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@graphprotocol/cost-model
> node-pre-gyp install --fallback-to-build=false --update-binary || yarn build-release

node-pre-gyp ERR! install response status 502 Bad Gateway on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v83-linux-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: response status 502 Bad Gateway on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v83-linux-x64.tar.gz
node-pre-gyp ERR! stack     at /home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
node-pre-gyp ERR! System Linux 5.4.0-99-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false" "--update-binary"
node-pre-gyp ERR! cwd /home/graph/.npm-global/lib/node_modules/@graphprotocol/indexer-cli/node_modules/@graphprotocol/cost-model
node-pre-gyp ERR! node -v v14.20.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok
response status 502 Bad Gateway on https://github.com/graphprotocol/agora/releases/download/v0.1.14/graphprotocol-agora-plugin-v0.1.14-node-v83-linux-x64.tar.gz
sh: 1: yarn: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @graphprotocol/cost-model@0.1.14 install: `node-pre-gyp install --fallback-to-build=false --update-binary || yarn build-release`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @graphprotocol/cost-model@0.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/graph/.npm/_logs/2022-09-06T22_56_56_430Z-debug.log
ERROR: Service 'cli' failed to build: The command '/bin/sh -c npm i -g @graphprotocol/indexer-cli@0.20.1 --registry https://registry.npmjs.org/ --unsafe-perm=true' returned a non-zero code: 1
```

**Comment by Stakecraft** [comment]
fixed by rerun the process one more time
